defaults:
    - dataset: semantic_kitti
    - visual_model: lseg  #open_scene
    - _self_

paths:
    all_data: 'data'

semantic_grounding: True

num_particles: 512  # 1024
std_t: 0.1
std_rot: 0.1
num_samples: 4096  # 1024
in_3D: False

particles_batch_size: 32 # 32, 256 looks good
rays_loss_batch_size: 16  # 10
sampling: 'default'


init_std_x: 0.3
init_std_y: 0.3

global_localization:
    active: False
    distances: []

vis:
    demo: False
    floor: False
    plot_gt: True
    plot_estimated: True
    plot_particles: True
    particles_stride: 2
    num_colors: 200
