defaults:
    - dataset: vlmaps
    - visual_model: lseg  #open_scene
    - _self_

paths:
    all_data: 'data'

semantic_grounding: True

num_particles: 1024  # 256 1024
num_samples: 1024  # 4096 1024
in_3D: False

particles_batch_size: 128 # 32, 256
rays_loss_batch_size: 16  # 10
sampling: 'default'


init_std_x: 0.3
init_std_y: 0.3

odom:
    rot_x_std: 0.0
    rot_y_std: 0.1
    rot_z_std: 0.0
    x_std: 0.1
    y_std: 0.0
    z_std: 0.1

global_localization:
    active: False
    distances: [2., 1., 0.5, 0.2, 0.1]

vis:
    demo: False
    floor: False
    plot_gt: True
    plot_estimated: True
    plot_particles: True
    particles_stride: 32
    num_colors: 200