defaults:
    - dataset: semantic_kitti
    - visual_model: xdecoder  #open_scene
    - _self_

paths:
    all_data: 'data'

semantic_grounding: False

num_particles: 256
num_samples: 256

particles_batch_size: 32
rays_loss_batch_size: 16
sampling: 'default'


init_std_x: 0.3
init_std_y: 0.3
init_std_th: 0.1

odom:
    rot_x_std: 0.0
    rot_y_std: 0.1
    rot_z_std: 0.0
    x_std: 0.1
    y_std: 0.0
    z_std: 0.1

global_localization:
    distances: []

vis:
    demo: False
    floor: False
    plot_gt: True
    plot_data: False
    plot_rays: False
    plot_particles: True
    particles_stride: 16
    map_stride: 40
    num_colors: 500
    odom_stride: 20
    axes_length: 2.0
    axes_radius: 0.1
    frustum_scale: 4.