mesh_max_res: 0.01 # in meters
sem_gt_from_mesh: False


"00":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
"01":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
"02":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
"03":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
"04":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
"05":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
"06":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
"07":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
"08":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
"09":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
"10":
    min_height: -0.3  # relative to the floor
    max_height: 1.5 # relative to the camera init height
    resolution: 0.05
    max_level: 13
    shift_x: 0
    shift_y: 0
    