mesh_max_res: 0.01 # in meters
sem_gt_from_mesh: True

5LpN3gDmAk7_1:
  min_height: -0.3  # relative to the floor
  max_height: 1.5 # relative to the camera init height
  resolution: 0.02
  max_level: 11
  shift_x: 0
  shift_y: 0

JmbYfDe2QKZ_1:
  min_height: -0.3
  max_height: 1.1
  resolution: 0.02
  max_level: 11
  shift_x: 0
  shift_y: 0

YmJkqBEsHnH_1:
  min_height: -100.
  max_height: 2.
  resolution: 0.02
  max_level: 11
  shift_x: 0
  shift_y: 0

gTV8FGcVJC9_1:
  min_height: -2.
  max_height: 0.8
  resolution: 0.02
  max_level: 12
  shift_x: 0
  shift_y: 0

jh4fc5c5qoQ_1:
  min_height: -1.
  max_height: 1.1
  resolution: 0.02
  max_level: 11
  shift_x: 0
  shift_y: 0


JmbYfDe2QKZ_2:
  min_height: -1.
  max_height: 0.7
  resolution: 0.02
  max_level: 11
  shift_x: 0
  shift_y: 0

UwV83HsGsw3_1:
  min_height: -2
  max_height: 0.8
  resolution: 0.02
  max_level: 11
  shift_x: 0
  shift_y: 0

mJXqzFtmKg4_1:
  min_height: -1
  max_height: 1.5
  resolution: 0.02
  max_level: 12
  shift_x: 0
  shift_y: 0

ur6pFq6Qu1A_1:
  min_height: -1
  max_height: 0.7
  resolution: 0.02
  max_level: 12
  shift_x: 0
  shift_y: 0

Vt2qJdWjCF2_1:
  min_height: -1
  max_height: 0.7
  resolution: 0.02
  max_level: 13
  shift_x: 0
  shift_y: 0