download_poses: False   # don't download if exists

rgb: true
depth: true
semantic: true
step: 3

resolution:
    w: 1024
    h: 64 #720, currently it is always square in simulation
camera_height: 1.5

base2cam_rot: [1, 0, 0, 0, -1, 0, 0, 0, -1]
base_forward_axis: [0, 0, -1]
base_left_axis: [-1, 0, 0]
base_up_axis: [0, 1, 0]
# cam_calib_mat: [540, 0, 540, 0, 540, 360, 0, 0, 1]  # or get_sim_cam_mat_with_fov from vlmaps.utils.mapping_utils
hfov: 360 # back_rgb_sensor_spec.hfov -> Deg(90)

ignore_indx: -1000